### ISSUE TITLE
Write readme, update output to work on newer version

### ISSUE THREAD

**Issue by crxssed7** [errornonamer/wal-vivaldi#1]
Hi, I just stumbled upon this script and was wondering if it works? And if it does, how do I go about applying the CSS to Vivaldi?

**Comment by errornonamer** [comment]
I haven't gotten to fixing the CSS output since Vivaldi 5.0 broke it. so no, it doesn't work with Vivaldi 5.0+

If you're okay using the old version, you can apply it by enabling custom CSS on vivaldi://experiments and setting custom ui modifications setting under appearance to the directory that contains generated CSS file

**Comment by crxssed7** [comment]
Hi @errornonamer, thanks for the reply. I'm in no rush, so I think I can wait for the next CSS update :)
